apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ytterbic-flyingfish-java-springboot 
  janus-idp.io/tekton: ytterbic-flyingfish-java-springboot
  backstage.io/kubernetes-id: ytterbic-flyingfish-java-springboot
  backstage.io/kubernetes-namespace: rhtap-e2e-ci 
  app.kubernetes.io/part-of: ytterbic-flyingfish-java-springboot
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  